
  "before_install": [
    "sudo apt-get update -myqq",
    "sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++"
  ],
  "language": "node_js",
  "php": 7.0,
  "git": {
    "depth": 10
  },
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
